### ISSUE TITLE
麻烦把README里的运行方式改改

### ISSUE THREAD

**Issue by yumi6666** [Lensual/bilibilisearch#11]
作者你好，麻烦把README里的运行方式改改~
虽然程序直到今天还能稳定运行，但对于没有Node.js经验的开发者来说，node run start 这个误导真的会浪费他们人生啊啊啊啊啊~

**Comment by Lensual** [comment]
不好意思，很久前的代码，我当时的水平也不过瞎折腾nodejs而已
此项目不考虑维护，但大致原理可以借鉴
（自己上去开f12抓抓包，写个excel导出，控制下请求速度就完事了

**Comment by Soul-Charge** [comment]
> 作者你好，麻烦把README里的运行方式改改~ 虽然程序直到今天还能稳定运行，但对于没有Node.js经验的开发者来说，node run start 这个误导真的会浪费他们人生啊啊啊啊啊~

谢谢你，我说怎么用node run start 和 node run app.js都不行，原来直接node app.js就行了
